version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "/app/node_modules"
      - ./:/app/
    ports:
      - "4200:4200"
    command:
      ng serve --host 0.0.0.0
